// components/avatar/Thinking.svelte
<script lang="ts">
    import * as Accordion from "$lib/components/ui/accordion";
    import { Lightbulb } from "lucide-svelte";
    import MarkdownBlock from "./MarkdownBlock.svelte";
    import { tick } from "svelte";

    let {
        content = "",
        isThinking = false,
        onToggled = () => {},
    } = $props<{
        content: string;
        isThinking: boolean;
        onToggled: () => void;
    }>();

    let isUserScrolling = $state(false);
    let isOpenByUser = $state(false);

    let contentContainer: HTMLDivElement;
    let scrollTimeout: ReturnType<typeof setTimeout>;

    let accordionValue = $derived(
        isThinking || isOpenByUser ? "item-1" : undefined,
    );

    $effect(() => {
        const _dependency = content;

        if (contentContainer && isThinking && !isUserScrolling) {
            // Use tick() to wait for the DOM to update before scrolling.
            tick().then(() => {
                contentContainer.scrollTop = contentContainer.scrollHeight;
            });
        }
    });

    const handleScroll = () => {
        if (!contentContainer) return;
        isUserScrolling = true;
        clearTimeout(scrollTimeout);

        const isAtBottom =
            contentContainer.scrollTop + contentContainer.clientHeight >=
            contentContainer.scrollHeight - 10;

        if (isAtBottom) {
            isUserScrolling = false;
        } else {
            scrollTimeout = setTimeout(() => {
                isUserScrolling = false;
            }, 2000);
        }
    };
</script>

<div
    class="my-4 border border-gray-300 rounded-lg px-2"
    class:thinking={isThinking}
>
    <Accordion.Root class="w-full" type="single" value={accordionValue}>
        <Accordion.Item value="item-1" class="p-0">
            <Accordion.Trigger
                class="text-sm font-medium"
                onclick={() => {
                    if (!isThinking) {
                        isOpenByUser = !isOpenByUser;
                        setTimeout(() => {
                            onToggled();
                        }, 200);
                    }
                }}
                disabled={isThinking}
            >
                <div class="flex items-center">
                    <Lightbulb />
                    {#if isThinking}
                        <span class="thinking-indicator"> Thinking... </span>
                    {:else}
                        Thinking
                    {/if}
                </div>
            </Accordion.Trigger>
            <Accordion.Content>
                <div
                    class="thinking-content text-xs"
                    bind:this={contentContainer}
                    onscroll={handleScroll}
                >
                    <MarkdownBlock {content} />
                </div>
            </Accordion.Content>
        </Accordion.Item>
    </Accordion.Root>
</div>

<style>
    .thinking-indicator {
        display: inline-flex;
        align-items: center;
    }

    .thinking :global([data-state="open"]),
    .thinking :global([data-state="closed"]) {
        animation: none !important;
        transition: none !important;
    }

    .thinking-content {
        max-height: 300px;
        overflow-y: auto;
        scroll-behavior: auto;
    }
</style>

// src/components/avatar/Thinking.tsx
import { useState, useEffect, useRef } from 'react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Lightbulb } from 'lucide-react';
import MarkdownBlock from './MarkdownBlock';

interface ThinkingProps {
  content: string;
  isThinking: boolean;
  onToggled: () => void;
}

export default function Thinking({ content = "", isThinking = false, onToggled = () => {} }: ThinkingProps) {
  const [isUserScrolling, setIsUserScrolling] = useState(false);
  const [isOpenByUser, setIsOpenByUser] = useState(false);
  const contentContainerRef = useRef<HTMLDivElement>(null);
  const scrollTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  const accordionValue = isThinking || isOpenByUser ? "item-1" : undefined;

  useEffect(() => {
    // When content changes, check if we need to scroll
    if (contentContainerRef.current && isThinking && !isUserScrolling) {
      // Use setTimeout to wait for the DOM to update before scrolling
      setTimeout(() => {
        if (contentContainerRef.current) {
          contentContainerRef.current.scrollTop = contentContainerRef.current.scrollHeight;
        }
      }, 0);
    }
  }, [content, isThinking, isUserScrolling]);

  const handleScroll = () => {
    if (!contentContainerRef.current) return;
    setIsUserScrolling(true);
    clearTimeout(scrollTimeoutRef.current!);

    const isAtBottom =
      contentContainerRef.current.scrollTop + contentContainerRef.current.clientHeight >=
      contentContainerRef.current.scrollHeight - 10;

    if (isAtBottom) {
      setIsUserScrolling(false);
    } else {
      scrollTimeoutRef.current = setTimeout(() => {
        setIsUserScrolling(false);
      }, 2000);
    }
  };

  const handleToggle = () => {
    if (!isThinking) {
      setIsOpenByUser(!isOpenByUser);
      setTimeout(() => {
        onToggled();
      }, 200);
    }
  };

  return (
    <>
      <style dangerouslySetInnerHTML={{
        __html: `
        .thinking-indicator {
          display: inline-flex;
          align-items: center;
        }

        .thinking [data-state="open"],
        .thinking [data-state="closed"] {
          animation: none !important;
          transition: none !important;
        }

        .thinking-content {
          max-height: 300px;
          overflow-y: auto;
          scroll-behavior: auto;
        }
        `
      }} />
      <div
        className={`my-4 border border-gray-300 rounded-lg px-2 ${isThinking ? 'thinking' : ''}`}
      >
        <Accordion className="w-full" type="single" value={accordionValue}>
          <AccordionItem value="item-1" className="p-0">
            <AccordionTrigger
              className="text-sm font-medium"
              onClick={handleToggle}
              disabled={isThinking}
            >
              <div className="flex items-center">
                <Lightbulb />
                {isThinking ? (
                  <span className="thinking-indicator"> Thinking... </span>
                ) : (
                  "Thinking"
                )}
              </div>
            </AccordionTrigger>
            <AccordionContent>
              <div
                className="thinking-content text-xs"
                ref={contentContainerRef}
                onScroll={handleScroll}
              >
                <MarkdownBlock content={content} />
              </div>
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </>
  );
}
